# Redis, MySQL 자동 실행용
# 개발: docker desktop실행 중이어야 함 -> 터미널 켜고 이 파일 위치에서 docker-compose up -d
# 또는 ubuntu 켜서 sudo service docker start -> 이 파일 위치에서 docker-compose up -d
# 운영: ssh접속 후 바로 docker-compose up -d
# 한 번만 하면 이후 자동으로 켜줌

version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: excuse-bundle-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes  # 데이터 영속성

  mysql:
    image: mysql:8.0
    container_name: excuse-bundle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: excuse_bundle
    ports:
      - "13306:3306"
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  redis-data:
  mysql-data: