spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: ${h2.username}
    password: ${h2.password}
  h2:
    console:
      enabled: true
      path: /h2
