app:
  project:
    name: excuse_dict
  server:
    host: localhost

cors:
  allowed:
    origins: http://localhost:3000
spring:
  profiles:
    include: secret # appllcation-secret.yml 임포팅
  datasource:
    url: jdbc:mysql://${app.server.host}:13306/${app.project.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #운영시엔 validate
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true # 콘솔 디버깅
        smtp:
          auth: true
          timeout: 30000 # 30초
          connection-timeout: 10000
          write-timeout: 30000
          starttls:
            enable: true
            required: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
jwt:
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 50000