server:
  port: 8081

admin:
  emails: ${ADMIN_EMAILS}

app:
  server:
    host: localhost

cors:
  allowed:
    origins: http://localhost:3000
spring:
  application:
    name: excuse_dict
  profiles:
    include: secret # appllcation-secret.yml 임포팅
  datasource:
    url: jdbc:mysql://${app.server.host}:13306/${spring.application.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never # data.sql 자동 실행여부 제어 (always / embedded / never)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update # create: 앱 시작할 때마다 리셋, update: 변경사항만 반영, validate: 스키마 검증만
    show-sql: true
    defer-datasource-initialization: true # datasource 초기화를 Hibernate의 테이블 생성 후로 연기 -> data.sql 실행 연기
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        debug: true # 콘솔 디버깅
        smtp:
          auth: true
          timeout: 30000 # 30초
          connection-timeout: 10000
          write-timeout: 30000
          starttls:
            enable: true
            required: true
  web:
    resources:
      add-mappings: true
#logging:
  #level:
    #org.springframework.web: DEBUG
    #org.springframework.security: DEBUG
    #org.springframework.web.servlet.DispatcherServlet: DEBUG
    #org.springframework.web.filter: DEBUG
    #org.springframework.web.context.request.async.WebAsyncManager: DEBUG
    #org.springframework.security.concurrent: DEBUG
    #org.springframework.security.task: DEBUG
    #reactor.netty.http: DEBUG
    #org.springframework.security.web.access: DEBUG
    #org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration: DEBUG
    #org.springframework.boot.sql.init: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: httptrace
jwt:
  key: ${JWT_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 50000

recaptcha:
  secret_key: ${RECAPTCHA_SECRET_KEY}