
INSERT INTO tags (value, type) VALUES
-- 사고 관련
('감전', 'ACCIDENT'),
('골절', 'ACCIDENT'),
('넘어짐', 'ACCIDENT'),
('도난', 'ACCIDENT'),
('미끄러짐', 'ACCIDENT'),
('물에빠짐', 'ACCIDENT'),
('베임', 'ACCIDENT'),
('분실', 'ACCIDENT'),
('부딪힘', 'ACCIDENT'),
('사고', 'ACCIDENT'),
('염좌', 'ACCIDENT'),
('응급상황', 'ACCIDENT'),
('접촉사고', 'ACCIDENT'),
('자전거사고', 'ACCIDENT'),
('찔림', 'ACCIDENT'),
('찰과상', 'ACCIDENT'),
('추돌사고', 'ACCIDENT'),
('타박상', 'ACCIDENT'),
('탈구', 'ACCIDENT'),
('폭행', 'ACCIDENT'),
('화상', 'ACCIDENT'),
('교통사고', 'ACCIDENT'),

-- 회사 관련
('미팅', 'COMPANY'),
('반차', 'COMPANY'),
('발표', 'COMPANY'),
('세미나', 'COMPANY'),
('야근', 'COMPANY'),
('업무', 'COMPANY'),
('연차', 'COMPANY'),
('워크샵', 'COMPANY'),
('조퇴', 'COMPANY'),
('지각', 'COMPANY'),
('출장', 'COMPANY'),
('컨퍼런스', 'COMPANY'),
('프로젝트', 'COMPANY'),
('회사', 'COMPANY'),
('회의', 'COMPANY'),

-- 경조사
('결혼식', 'EVENT'),
('경조사', 'EVENT'),
('기념일', 'EVENT'),
('동창회', 'EVENT'),
('돌잔치', 'EVENT'),
('모임', 'EVENT'),
('백일잔치', 'EVENT'),
('생일', 'EVENT'),
('성년식', 'EVENT'),
('입학식', 'EVENT'),
('장례식', 'EVENT'),
('졸업식', 'EVENT'),
('첫돌', 'EVENT'),
('칠순잔치', 'EVENT'),
('파티', 'EVENT'),
('환갑잔치', 'EVENT'),
('회갑연', 'EVENT'),

-- 가족 관련
('가족', 'FAMILY'),
('가족행사', 'FAMILY'),
('부모님', 'FAMILY'),
('반려동물', 'FAMILY'),
('아이', 'FAMILY'),
('이사', 'FAMILY'),
('제사', 'FAMILY'),
('조부모', 'FAMILY'),
('집안일', 'FAMILY'),
('형제자매', 'FAMILY'),
('명절', 'FAMILY'),

-- 건강 관련
('감기', 'HEALTH'),
('건강검진', 'HEALTH'),
('관절염', 'HEALTH'),
('구토', 'HEALTH'),
('근육통', 'HEALTH'),
('기침', 'HEALTH'),
('담결림', 'HEALTH'),
('독감', 'HEALTH'),
('두통', 'HEALTH'),
('라미네이트', 'HEALTH'),
('라식/라섹', 'HEALTH'),
('목감기', 'HEALTH'),
('목아픔', 'HEALTH'),
('몸살', 'HEALTH'),
('배탈', 'HEALTH'),
('발열', 'HEALTH'),
('발치', 'HEALTH'),
('병원예약', 'HEALTH'),
('복통', 'HEALTH'),
('사랑니', 'HEALTH'),
('생리불순', 'HEALTH'),
('생리통', 'HEALTH'),
('설사', 'HEALTH'),
('소화불량', 'HEALTH'),
('식중독', 'HEALTH'),
('어깨결림', 'HEALTH'),
('어지러움', 'HEALTH'),
('연골염', 'HEALTH'),
('오한', 'HEALTH'),
('임플란트', 'HEALTH'),
('장염', 'HEALTH'),
('치과예약', 'HEALTH'),
('치통', 'HEALTH'),
('컨디션난조', 'HEALTH'),
('통원치료', 'HEALTH'),
('편두통', 'HEALTH'),
('허리아픔', 'HEALTH'),
('현기증', 'HEALTH'),
('눈병', 'HEALTH'),
('근육통', 'HEALTH'),
('알레르기', 'HEALTH'),
('예방접종', 'HEALTH'),

-- 집 설비
('가스누출', 'HOME_FACILITY'),
('가스점검', 'HOME_FACILITY'),
('난방안됨', 'HOME_FACILITY'),
('누수', 'HOME_FACILITY'),
('단수', 'HOME_FACILITY'),
('도배', 'HOME_FACILITY'),
('도어락고장', 'HOME_FACILITY'),
('문짝고장', 'HOME_FACILITY'),
('방역', 'HOME_FACILITY'),
('보일러고장', 'HOME_FACILITY'),
('상하수도', 'HOME_FACILITY'),
('세탁기고장', 'HOME_FACILITY'),
('싱크대막힘', 'HOME_FACILITY'),
('에어컨수리', 'HOME_FACILITY'),
('열쇠분실', 'HOME_FACILITY'),
('온수끊김', 'HOME_FACILITY'),
('인터넷설치', 'HOME_FACILITY'),
('전기공사', 'HOME_FACILITY'),
('전기누전', 'HOME_FACILITY'),
('정전', 'HOME_FACILITY'),
('집수리', 'HOME_FACILITY'),
('냉장고고장', 'HOME_FACILITY'),
('하수도역류', 'HOME_FACILITY'),
('화장실막힘', 'HOME_FACILITY'),

-- 연애
('기념일', 'RELATIONSHIP'),
('다툼', 'RELATIONSHIP'),
('데이트', 'RELATIONSHIP'),
('미팅', 'RELATIONSHIP'),
('부모님인사', 'RELATIONSHIP'),
('선물준비', 'RELATIONSHIP'),
('소개팅', 'RELATIONSHIP'),
('연애', 'RELATIONSHIP'),
('연애상담', 'RELATIONSHIP'),
('이별', 'RELATIONSHIP'),
('프러포즈', 'RELATIONSHIP'),

-- 종교 관련
('교회', 'RELIGIOUS'),
('기도회', 'RELIGIOUS'),
('법회', 'RELIGIOUS'),
('봉사활동', 'RELIGIOUS'),
('선교', 'RELIGIOUS'),
('성경공부', 'RELIGIOUS'),
('성당', 'RELIGIOUS'),
('성지순례', 'RELIGIOUS'),
('수련회', 'RELIGIOUS'),
('예배', 'RELIGIOUS'),
('절', 'RELIGIOUS'),
('종교', 'RELIGIOUS'),
('종교행사', 'RELIGIOUS'),
('주일학교', 'RELIGIOUS'),
('미사', 'RELIGIOUS'),

-- 교통 관련
('교통', 'TRANSPORT'),
('교통체증', 'TRANSPORT'),
('도로공사', 'TRANSPORT'),
('버스', 'TRANSPORT'),
('버스파업', 'TRANSPORT'),
('시위', 'TRANSPORT'),
('지하철', 'TRANSPORT'),
('지하철지연', 'TRANSPORT'),
('택시', 'TRANSPORT'),

-- 날씨 관련
('더위', 'WEATHER'),
('미세먼지', 'WEATHER'),
('날씨', 'WEATHER'),
('폭설', 'WEATHER'),
('폭우', 'WEATHER'),
('장마', 'WEATHER'),
('추위', 'WEATHER'),
('태풍', 'WEATHER'),
('황사', 'WEATHER');

-- 기타
('고소/고발', 'ETC');
('새똥', 'ETC');
